### PR TITLE
IX multiselect

### LINKED ISSUE #6587: IX Support for multiselect properties
Add backend support for multiselect and select properties.

- Right now the backend does not validate the type of extractors you can create, we want to add it.
- For training Uwazi should send the whole PDF as context
  -  Can the extracted paragraphs be enough for this?
- The suggestion is an array of values and the backend should be able to support this
   -  Are this the IDs of the thesaurus or the label ?
-  What happens when you update the thesaurus after got some suggestions?

### PR DESCRIPTION
**Pull request by fnocetti**
fixes #6587 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Comment by LaszloKecskes** [comment]
Merging ignoring cypress flakiness. All tests passed on CI at least once, and all tests pass locally.

**Comment by serena-huridocs** [comment]
Hi everyone! @pddocs and I have tested it in one of the staging instances but were not able to add Select/Multiselect properties as extractors. Could you please let us know where (in which instances) this can be tested so that we can report results back to you?

**Comment by LaszloKecskes** [comment]
@serena-huridocs  This is only backend portion of the work, the full feature is not on staging yet. The front-end issue is #6633.

**Comment by serena-huridocs** [comment]
Got you, thanks, @LaszloKecskes!

**Pull request merged**
