### PR TITLE
5597 merge content repo

### LINKED ISSUE #5597: Merge content repo into uwazi
Instead of getting the translations to an external [github repository](https://github.com/huridocs/uwazi-contents)  we will ship every app with its own version of the contents.
Having this in a separate repository has its advantages (correcting types and having immediate effect without having to deploy)  but complicates things considerably, we prefer having everything together and ship it with the app, doing more frequent (hotfixes) deploys if needed.

#5444 added a routine to check inconsistencies between the database and the translation contents by language, this should be updated to check from the local contents once these have been moved.

### LINKED ISSUE #5639: Available default translation for English (en).
**Is your feature request related to a problem? Please describe.**
Let's take an instance that has only non-English UIs like Amharic (am). You later want to add English UI: currently Uwazi does not have default translation available for English (en). This feature is currently already available for select languages in Uwazi such as for Arabic. 

**Describe the solution you'd like**
Enable available default translation for English (en). 

**Have you considered an alternative?**
Importing the systems English UI terms and/or typing them in manually, from the Translation settings. 

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by fnocetti**
fixes #5597
fixes #5639 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Review by mfacar — APPROVED** [review]
LGTM!  I only have a suggestion regarding the comparison script, I think it could be worth removing the argument ```outdir``` and setting the path by default with the location of the contents for translations, getting the same result like ```yarn compare-translations --update --outdir=./contents/ui-translations/  ```

**Review by daneryl — APPROVED** [review]
LGTM !

**Comment by fnocetti** [comment]
> LGTM! I only have a suggestion regarding the comparison script, I think it could be worth removing the argument `outdir` and setting the path by default with the location of the contents for translations, getting the same result like `yarn compare-translations --update --outdir=./contents/ui-translations/ `

That's a good one! I implemented the change, could you please take a quick look?

**Comment by fnocetti** [comment]
> LGTM !

Thank you @daneryl !

**Pull request merged**
