### PR TITLE
3641 render thesauri category

### LINKED ISSUE #3641: Render thesauri category when showing metadata (13 pts)
Thesaurus can have the values grouped in categories, as users we want the category rendered with the values so there is more context for those values.

Screenshot 2021-05-03 at 10 26 50
Screenshot 2021-05-03 at 10 26 58

⚠️ 
Right now we are denormalising the labels of the values selected, categories will require to be denormalised too

```
[
{value: dj28djh, label: 'Art1', parent: {value: 344sd, label: Laws Chapter 2}},
{value: d2as8d, label: 'Art2', parent: {value: 321sf, label: Laws Chapter 1}},
{value: d2as8d, label: 'Art3', parent: null}
]
```

Updating the thesauri should update the denormalised value, actions like:
- Rename a group

### PR DESCRIPTION
**Pull request by konzz**
fixes #3641 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Review by fnocetti — COMMENTED** [review]
The code looks good!
Things to consider during testing:
- [x] All denormalization scenarios (set, unset, name update)
- [x] Translations
- [x] Sync
- [x] UI

**Comment by fnocetti** [comment]
There's a bug when changing a nested thesauri value:
- Have a thesauri with the following structure:

   - parent
     - first child
     - second child

- Edit the name of `first child` to anything else.
- You get `TypeError: Cannot read property 'values' of undefined`

**Comment by fnocetti** [comment]
In view mode (sidebar / entity view) the values are shown non-translated:

- Have two languages.
- Have an the thesauri in the previous comment.
- Have a template that uses that thesauri and create an entity. Select a few values.
- Translate the thesauris (through the translations UI in the settings view) on the second language.
- Go to some entity view (sidebar or click the view button)

Result: the values are not translated. Note that they are translated in edit mode.

**Review by fnocetti — CHANGES_REQUESTED** [review]
@konz it looks good in general. Please have a look at my comments. Thanks!

**Comment by konzz** [comment]
@fnocetti Fixed the first scenario, cant replicate the second one tho, let's have a call for it

**Comment by fnocetti** [comment]
> @fnocetti Fixed the first scenario, cant replicate the second one tho, let's have a call for it

@konzz I'm still able to reproduce the second scenario. Looks like it happens for nested thesauri only, but I checked and it also happens in the `development` branch. Let's discuss how to proceed.

I'll append some screenshots anyways:

This is what I get in spanish in the sidepanel after translation:

Screen Shot 2021-07-12 at 12 57 44 PM

This is what I see in edit mode (for comparison reasons):

Screen Shot 2021-07-12 at 12 58 01 PM

**Review by fnocetti — APPROVED** [review]

**Pull request merged**
