### PR TITLE
6824 - Silence warnings for React 19 deprecated APIs

### LINKED ISSUE #6824: Hundreds of warnings for deprecated features of the React next version
After #6752 and as it's described in the [upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide), there are hundreds of warnings in the browser console for deprecated APIs. It is ideal to silence these warnings while being aware of the problematic areas by decorating the window.console.error function.

### PR DESCRIPTION
**Pull request by mfacar**
fixes #6824

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

### CODE REVIEW

**Review by Zasa-san — APPROVED** [review]
LGTM! You can still see the errors on the terminal when loading for the first time. I think that's a good thing so that we don't forget about them.
 
That is my only concern, that we have no way of remembering these silenced errors exist, except the case I mentioned above. Is there be a way that we could transform them into warning, instead of errors, on the console?

**Comment by mfacar** [comment]
@Zasa-san, I think it is possible to call a `console.warn` but it would imply having the same hundreds of messages in the browser console, maybe is better to keep the warnings in the server terminal while we start planning the upgrade to React 19, which was already released as RC a month ago.

**Comment by Zasa-san** [comment]
> @Zasa-san, I think it is possible to call a `console.warn` but it would imply having the same hundreds of messages in the browser console, maybe is better to keep the warnings in the server terminal while we start planning the upgrade to React 19, which was already released as RC a month ago.

Makes sense! 👍

**Comment by mfacar** [comment]
Information extraction cypress tests consistently fail across all the PRs, so ignoring that suite

**Pull request merged**
